### ISSUE TITLE
not support M1 cpu

### ISSUE THREAD

**Issue by tian-jie** [wwwHui/DeepReinforcementLearning#1]
Hi Guy,

I tried your code, that is rare code I can run with such a simple environment configuration!

I can run using your code. But I tried to changed a little in order to support M1 GPU, but it show me some error.
Here is what  I changed to support M1 GPU: (last line is original code)

```
    self.device = torch.device("mps")
    if self.device.type == "mps":
        print('using mps')
    else:
        self.device = torch.device(f"cuda:{gpu_id}" if (torch.cuda.is_available() and (gpu_id >= 0)) else "cpu")
```

it actually gave me the response "using mps", but I got some error here:

```
2024-04-08 18:20:11.658222 start
using mps
Traceback (most recent call last):
  File "/Users/tianjie/workspaces/dqn_wwwHui/dqn/dqn.py", line 475, in <module>
    function_run()
  File "/Users/tianjie/workspaces/dqn_wwwHui/dqn/dqn.py", line 469, in function_run
    train_dqn_for_cartpole()
  File "/Users/tianjie/workspaces/dqn_wwwHui/dqn/dqn.py", line 465, in train_dqn_for_cartpole
    train_agent(args)
  File "/Users/tianjie/workspaces/dqn_wwwHui/dqn/dqn.py", line 291, in train_agent
    buffer_items = agent.explore_env(env, args.horizon_len * args.eval_times, if_random=True)
  File "/Users/tianjie/workspaces/dqn_wwwHui/dqn/dqn.py", line 209, in explore_env
    actions[i] = action
RuntimeError: length >= offset INTERNAL ASSERT FAILED at "/private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_83_m9l5ufr/croot/pytorch_1686041389610/work/aten/src/ATen/mps/MPSStream.mm":122, please report a bug to PyTorch. 

```

hope you have any ideas on it.

**Comment by wwwHui** [comment]
Sorry, I don't have an M1 device, so I can't test it. You can try to confirm if the shapes, devices, and other properties of "actions" and "action" are consistent.

**Comment by wwwHui** [comment]
Please replace ` actions[i] = action` in the explore_env function with `actions[i] = action.to(self.device)`.
